### ISSUE TITLE
Target data processing error

### ISSUE THREAD

**Issue by timpeti76** [EpistasisLab/tpot#1027]
I'm new to tpot and have been familiarizing myself with the features by going through some tutorials. As a next step, I loaded in some of my own data into tpot instead of the Iris data-set. However, when compiling, I get the following error:

![image](https://user-images.githubusercontent.com/61450299/75225787-917af500-57ab-11ea-9822-eae3b4eeb445.png)

The training target 1-D array looks like this:

![image](https://user-images.githubusercontent.com/61450299/75225986-d737bd80-57ab-11ea-9f93-2f5056d6eb5c.png)

When I use the Iris-target array instead, it compiles and runs properly. What am I doing wrong?

Thank you for your help!

Tim

**Comment by weixuanfu** [comment]
I think the issue is that `Y=df.values[0:150, 10]` make `Y` a non-numerical object, which is not supported in TPOT. Please try to convert Y to np.int32 or np.float64 via `Y.astype(np.int32)` after `Y=df.values[0:150, 10]`or you could try Y=df.values["Target_Column"].values instead of `Y=df.values[0:150, 10]`.

**Comment by timpeti76** [comment]
Thank you for your quick response, converting to float via Y.astype(np.int32) did the trick!
