### ISSUE TITLE
TPOT MDT hangs after first optimization progress

### ISSUE THREAD

**Issue by sword134** [EpistasisLab/tpot#1105]
Hello I set a TPOT MDT function to run for 8 hours today, however to my disappointment it hadn't even progressed to the next generation, is this a bug?

tpot = TPOTClassifier(generations=None, population_size=10000, verbosity=2, max_time_mins=480, n_jobs=-1, periodic_checkpoint_folder="D:\\ReinforcementLearning\\XGBoost\\Output\\Checkpoints", config_dict="TPOT MDR")
tpot.fit(X_train, y_train)
tpot.export('D:\\ReinforcementLearning\\XGBoost\Output\\tpot_digits_pipeline.py')

**Comment by weixuanfu** [comment]
Those MDR methods from skrebate is very slow for dataset with a large number of features. How many features are there in your dataset?

Also in your example codes, I saw the `population_size=10000` which is too large for TPOT MDR due to its limited search space of hypeparameters. I suggest to set it as default value, 100.

**Comment by sword134** [comment]
@weixuanfu very well, I have 183 features, whats a recommended population size then? It explicitly says that a larger population size gives higher accuracy.

**Comment by weixuanfu** [comment]
I think population_size=100 should be enough for TPOT MDR.
