### ISSUE TITLE
Bound tpot to only optimize the ML classifier by given classifier args

### ISSUE THREAD

**Issue by tobilab** [EpistasisLab/tpot#1235]
To the best of my knowledge a TPOT.fit call optimizes a full pipeline including Feature Scaling, maybe Feature Selection ,.... , Classifier optimization.
How can i bound tpot to only specify the ML classifier arguments so that there is NO Feature Scaling and so on done?

I currently use the classifier config dict as follows e.g.:
`classifier_config_dict['xgboost.XGBClassifier'] = {
    'n_estimators': [100],
    'max_depth': range(1, 11),
    'learning_rate': [1e-3, 1e-2, 1e-1, 0.5, 1.],
    'subsample': np.arange(0.05, 1.01)
}`

And the i apply it to the TPOTClassifier: `TPOTClassifier(...,config_dict=classifier_config_dict)`

But the created pipelines do always contain other steps (like Feature Scaling and so on). This distorts the actual comparison of different classifiers.

Can someone please help me, maybe with a short example?

**Comment by JDRomano2** [comment]
You can fix this by defining a new config dict, rather than modifying and using an existing config that contains the unwanted preprocessing steps. Something like this:

```{python}
my_config_dict = {
    'xgboost.XGBClassifier': { 
        'n_estimators': [100],
        'max_depth': range(1, 11),
        'learning_rate': [1e-3, 1e-2, 1e-1, 0.5, 1.],
        'subsample': np.arange(0.05, 1.01) 
    },
    'sklearn.svm.LinearSVC': {
        'penalty': ["l1", "l2"],
        'loss': ["hinge", "squared_hinge"],
        'dual': [True, False],
        'tol': [1e-5, 1e-4, 1e-3, 1e-2, 1e-1],
        'C': [1e-4, 1e-3, 1e-2, 1e-1, 0.5, 1., 5., 10., 15., 20., 25.]
    },
    ...
}
```

And so on, with whichever estimators you want to use. If you want to ONLY test the XGBoost classifier, you would just have a block containing that config. Then you can use `my_config_dict` when you instantiate `TPOTClassifier`:

```{python}
clf = TPOTClassifier(...,config_dict=my_config_dict)
...
```

If you want to use many estimators and don't want to type all of them out, you can just copy/paste the default classifier config dict and remove the things you aren't interested in including in your pipelines, like found here: https://github.com/EpistasisLab/tpot/blob/6448bdb71ba08b4a0447c640d2f05a05e1affc21/tpot/config/classifier.py

How does this work for you?

**Comment by tobilab** [comment]
Thanks that helped me getting the things to work :)
