### ISSUE TITLE
Outlier Removal

### ISSUE THREAD

**Issue by jonathanng** [EpistasisLab/tpot#550]
I'm curious to know why outlier removal isn't part of the pipeline.

`scikit-learn` offers several outlier detection methods, and it seems simple to implement.

See here:

http://scikit-learn.org/stable/auto_examples/covariance/plot_outlier_detection.html#sphx-glr-auto-examples-covariance-plot-outlier-detection-py

**Comment by rhiever** [comment]
Hi @jonathanng,

AFAIK, scikit-learn pipelines do not work with transformers that change the number of instances (i.e., rows) in the dataset, because the target labels (i.e., `y`) would also need to be transformed as well. There would need to be a custom scikit-learn pipeline implementation that works with datasets of varying sample sizes.

**Comment by jonathanng** [comment]
I think you're right...

https://stackoverflow.com/questions/40279682/outlier-detection-in-scikit-learn-using-transformers-in-a-pipeline
