### ISSUE TITLE
Bug in displaying "Current best internal CV score: "

### ISSUE THREAD

**Issue by QuantumDamage** [EpistasisLab/tpot#612]
I'm using custom scoring function called "my_max_profit_constant" - which is supposed to be maximized. 

Subsequent iterations of tpot fit are giving:
```
...
Generation 2 - Current best internal CV score: 361.71999999999997
Generation 3 - Current best internal CV score: 353.12
...
Generation 7 - Current best internal CV score: 187.64000000000004
...
Generation 23 - Current best internal CV score: 9.840000000000012
...
Generation 28 - Current best internal CV score: 22.559999999999995
...
```
Above output looks like minimizing function.
But when I'm checking periodic checkpoint output, in comments there are lines:

```
# Score on the training set was:-361.71999999999997
# Score on the training set was:-353.12
# Score on the training set was:-187.64000000000004
# Score on the training set was:-9.840000000000012
# Score on the training set was:22.559999999999995

```
And those files look like they representing pipelines with ascending score.

So my guess is that there is bug in displaying score in runtime: "-" symbol is stripped or absolute value is taken.

**Comment by rhiever** [comment]
Oh, that is indeed a strange output. We do [use the absolute value](https://github.com/rhiever/tpot/blob/89d3ee6b4a48c6d411761ec13121006ac5ee59be/tpot/base.py#L782) when reporting the score of the best TPOT pipeline at each generation. We wrote TPOT assuming that the metrics being used within TPOT won't have a meaningful positive *and* negative value.

Judging from your other issue (#611), I am assuming that your metric is the amount of profit/loss (in terms of money) that the algorithm would have caused for you based on its performance on all of the training records. I believe that is an atypical metric design in ML. Typically we use metrics that quantify the amount of mismatch between the predicted value and the true value of the target.

That said, I think your metric can be supported in the current TPOT framework. Of course, your metric still works on the optimization side because TPOT will maximize any metric that doesn't have 'loss' or 'error' in the name. However, I think your metric could be better supported within TPOT if you devise a function of the metric that results in negative values being > 0 and positives values > all possible negative values. For example, your metric can return `profits + 1` if `profits >= 0`, and return `1.0 / abs(profits)` if `profits < 0`. That function would cause the metric to return an ever smaller value with more losses (i.e., negative profits) and an ever increasing value with more profits.

**Comment by weixuanfu** [comment]
Related issue #425

**Comment by QuantumDamage** [comment]
Actually I'm mainly using [Negative predictive value](https://en.wikipedia.org/wiki/Positive_and_negative_predictive_values#Negative_predictive_value) which gives results between 0 and 1 and it works as you designed.
I was just experimenting and found this behavior. Your explanation is reasonable and its OK for me ;)
Thanks for hint and reasons. 
I believe we can close this thread now.
