### ISSUE TITLE
CombineDFs(input_matrix, input_matrix) operator

### ISSUE THREAD

**Issue by bartdp1** [EpistasisLab/tpot#636]
Tpot evaluates the following pipeline:
`RandomForestClassifier(CombineDFs(input_matrix, input_matrix), RandomForestClassifier__bootstrap=True, RandomForestClassifier__criterion=entropy, RandomForestClassifier__max_features=0.15, RandomForestClassifier__min_samples_leaf=11, RandomForestClassifier__min_samples_split=15, RandomForestClassifier__n_estimators=100)`

If i understand correctly, this simply runs the classifier on a dataset with each column twice, leading to unnecessary computation times. Should there be mechanisms to avoid such cases?

**Comment by weixuanfu** [comment]
@bartdp1 The `combineDFs` in TPOT is to build pipeline in tree structure by merging data frame the prediction by other classifiers or  transformed features by transformers and then pass the data frame to next step.  But since pipelines is randomly generated in the beginning so this kind of combination can be generated. 

We had some discussions in the issue #152. I think in a future version of TPOT, there are two new parameters to disable the `CombineDFs` and  `StackingEstimator` respectively. For now, you could try one of my dev branch called [noCDF_noStacking](https://github.com/weixuanfu/tpot/tree/noCDF_noStacking) has a option named `simple_pipeline`, which can disable both `StackingEstimator` and `CombineDFs` if `simple_pipeline=True` (e.g. `TPOTClassifier(simple_pipeline=True)`). But it is noted that this dev branch is not fully tested yet. You may install this branch in your test environment via the command below:

```
pip install --upgrade --no-deps --force-reinstall git+https://github.com/weixuanfu/tpot.git@noCDF_noStacking
```

**Comment by weixuanfu** [comment]
I close this issue. Please feel free to re-open the issue (or comment further) if you have any more questions

**Comment by Ace7866** [comment]
Hi @weixuanfu .. I have a separate question about TPOT and wondering if I may be able to ask you here. I ran the classifier and it spit out the current best pipeline. Unfortunately I did not export the optimized pipeline to a separate .py file before exiting the kernel. Is there a way I can take the output shown in the attached image and plug it back into TPOT so I can use this optimized model to predict on my dataset? In other words, I do not know how to get back to this point without needing to restart the entire classifier. Is this possible? 
The optimized pipeline is using GradientBoostingClassifier with some feature engineering and transformations. Can I just tell TPOT to use this pipeline without needing to manually do the feature engineering myself and feeding result into GradientBoostingClassifier?




<img width="911" alt="TPOT_output" src="https://user-images.githubusercontent.com/58792096/223561559-4d80f093-a363-4678-a630-453156c55c88.png">
