### ISSUE TITLE
Ensembling functionality in TPOTs

### ISSUE THREAD

**Issue by miteshyadav** [EpistasisLab/tpot#656]
Does the final classifier obtained after using the TPOT only contain the best individual models or is it possible to get stacked estimators by ensembling different models?

**Comment by weixuanfu** [comment]
Hmm, for now TPOT cannot stack estimators for ensembling models. We have a idea about TPOTensemble #479 but it is very computational expensive. I suppose that you may want use the good pipelines in `tpot_object._pareto_front` since the final optimized pipeline was got from the pareto front (check [codes](https://github.com/EpistasisLab/tpot/blob/v0.9/tpot/base.py#L624-L630)) and you could optimized pipeline in pareto front to scikit-learn pipeline with [this one line of code](https://github.com/EpistasisLab/tpot/blob/v0.9/tpot/base.py#L677) (also it's the way to generate the final pipeline `tpot_object.fitted_pipeline_` within TPOT).
