### ISSUE TITLE
Precision and recall in multiclass classification

### ISSUE THREAD

**Issue by prabhant** [EpistasisLab/tpot#700]
Errors in multiclass scenario while using TPOT with another scoring measure than accuracy

## Context of the issue
I'm getting this error while using tpot on iris data and using any other scoring measure than accuracy.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    629                     verbose=self.verbosity,
--> 630                     per_generation_function=self._check_periodic_pipeline
    631                 )

/usr/local/lib/python3.5/dist-packages/tpot/gp_deap.py in eaMuPlusLambda(population, toolbox, mu, lambda_, cxpb, mutpb, ngen, pbar, stats, halloffame, verbose, per_generation_function)
    243         if per_generation_function is not None:
--> 244             per_generation_function()
    245 

/usr/local/lib/python3.5/dist-packages/tpot/base.py in _check_periodic_pipeline(self)
    916         """
--> 917         self._update_top_pipeline()
    918         if self.periodic_checkpoint_folder is not None:

/usr/local/lib/python3.5/dist-packages/tpot/base.py in _update_top_pipeline(self)
    708             if not self._optimized_pipeline:
--> 709                 raise RuntimeError('There was an error in the TPOT optimization '
    710                                    'process. This could be because the data was '

RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-68-b3eb03c9c133> in <module>()
      1 tpot = TPOTClassifier(generations=2, population_size=20, verbosity=3, scoring = em,config_dict='TPOT light')
----> 2 tpot.fit(X_train, y_train)
      3 print(tpot.score(X_test, y_test))

/usr/local/lib/python3.5/dist-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    660                     # raise the exception if it's our last attempt
    661                     if attempt == (attempts - 1):
--> 662                         raise e
    663             return self
    664 

/usr/local/lib/python3.5/dist-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    651                         self._pbar.close()
    652 
--> 653                     self._update_top_pipeline()
    654                     self._summary_of_best_pipeline(features, target)
    655                     # Delete the temporary cache before exiting

/usr/local/lib/python3.5/dist-packages/tpot/base.py in _update_top_pipeline(self)
    707 
    708             if not self._optimized_pipeline:
--> 709                 raise RuntimeError('There was an error in the TPOT optimization '
    710                                    'process. This could be because the data was '
    711                                    'not formatted properly, or because data for '

RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT `correctly.`

```

**Comment by weixuanfu** [comment]
Which scoring method? Could you please provide a example to reproduce the error?


On May 31, 2018 at 6:30 AM, <prabhant<mailto:notifications@github.com>> wrote:


Errors in multiclass scenario while using TPOT with another scoring measure than accuracy

Context of the issue

I'm getting this error while using tpot on iris data and using any other scoring measure than accuracy.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    629                     verbose=self.verbosity,
--> 630                     per_generation_function=self._check_periodic_pipeline
    631                 )

/usr/local/lib/python3.5/dist-packages/tpot/gp_deap.py in eaMuPlusLambda(population, toolbox, mu, lambda_, cxpb, mutpb, ngen, pbar, stats, halloffame, verbose, per_generation_function)
    243         if per_generation_function is not None:
--> 244             per_generation_function()
    245

/usr/local/lib/python3.5/dist-packages/tpot/base.py in _check_periodic_pipeline(self)
    916         """
--> 917         self._update_top_pipeline()
    918         if self.periodic_checkpoint_folder is not None:

/usr/local/lib/python3.5/dist-packages/tpot/base.py in _update_top_pipeline(self)
    708             if not self._optimized_pipeline:
--> 709                 raise RuntimeError('There was an error in the TPOT optimization '
    710                                    'process. This could be because the data was '

RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-68-b3eb03c9c133> in <module>()
      1 tpot = TPOTClassifier(generations=2, population_size=20, verbosity=3, scoring = em,config_dict='TPOT light')
----> 2 tpot.fit(X_train, y_train)
      3 print(tpot.score(X_test, y_test))

/usr/local/lib/python3.5/dist-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    660                     # raise the exception if it's our last attempt
    661                     if attempt == (attempts - 1):
--> 662                         raise e
    663             return self
    664

/usr/local/lib/python3.5/dist-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    651                         self._pbar.close()
    652
--> 653                     self._update_top_pipeline()
    654                     self._summary_of_best_pipeline(features, target)
    655                     # Delete the temporary cache before exiting

/usr/local/lib/python3.5/dist-packages/tpot/base.py in _update_top_pipeline(self)
    707
    708             if not self._optimized_pipeline:
--> 709                 raise RuntimeError('There was an error in the TPOT optimization '
    710                                    'process. This could be because the data was '
    711                                    'not formatted properly, or because data for '

RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT `correctly.`

**Comment by prabhant** [comment]
Hi, I tried precision, recall on iris dataset
```
tpot = TPOTClassifier(generations=2, population_size=20, verbosity=3, scoring = 'precision',config_dict='TPOT light')
tpot.fit(X_train, y_train)
```

**Comment by weixuanfu** [comment]
Ok, I understand what happened.

The `scoring = 'precision' ` in your codes is for binary targets only. Please try 'precision_macro' or other scores instead. It is documented in the [link](http://scikit-learn.org/stable/modules/model_evaluation.html#common-cases-predefined-values) and please check suffixes of f1.




On May 31, 2018 at 7:22 AM, <prabhant<mailto:notifications@github.com>> wrote:


Hi, I tried precision, recall on iris dataset

tpot = TPOTClassifier(generations=2, population_size=20, verbosity=3, scoring = 'precision',config_dict='TPOT light')
tpot.fit(X_train, y_train)
