### ISSUE TITLE
[Question] Different measurements per sample pre-processing

### ISSUE THREAD

**Issue by fferroni** [EpistasisLab/tpot#709]
Hello,

My classification dataset has a different number of features per example. This is because I get a different number of measurements per sample which I am trying to classify, like trying to classify a sentence, or classifying a sequence, or an unordered set of points.

I am wondering whether TPOT has the ability to explore using GA the featurizing step as well as the classifiers. For example, exploring whether taking min, max, standard deviation, count and other combinations of features on the measurements of a single sample would lead to a better classification.

Thanks!

**Comment by weixuanfu** [comment]
Hmm, for now TPOT cannot handle the samples with different number of measurements. You may try some sample selection methods first.

**Comment by rhiever** [comment]
Because TPOT adheres to the scikit-learn data requirements, we do not support datasets that have a varying number of features per sample.

However, it is possible to fit such a dataset into the scikit-learn data requirements by creating a column for every feature for every sample and simply placing a missing value (`NaN`) in a column when a sample does not have a value for that feature. From there, TPOT will use median imputation to "guess" the best value for that feature when a sample is missing that value.

You can also format your dataset as described above, but manually perform the imputation yourself. If you have a better sense of a numerical value that should be present when a feature is not available for a sample, this is a better option. One common example of this approach with text data is setting the feature = 0 when a word is not present in a sentence, and setting the feature = 1 when a word is present in a sentence.

**Comment by fferroni** [comment]
Ok, thank you for the fast replies
