### ISSUE TITLE
Feature selection/extraction

### ISSUE THREAD

**Issue by lefig** [EpistasisLab/tpot#742]
Hi all,

I would appreciate a little help with a question.

Firstly, I wish to express appreciation for this most excellent and productive tool. I have recently started to explore it's capabilities.

I have a query. Is there a way to review or access the features used when a model runs (before or after) the pipeline completes. Are these logged anywhere for instance?

Thank you and best regards

Fig

**Comment by weixuanfu** [comment]
Thank you! I appreciate the positive feedback. 

There is a related issue #735 although it is not a very simple work-around to access the features. 

We may add an attribute/function in TPOT object to output the features used in each step of pipeline.

**Comment by JainVikas** [comment]
@weixuanfu 👍  for the #735, and thank you for this awesome work.
Quick follow up, I am able to use the workaround if the fitted pipeline contains SelectFwe method, but in my case, fitted pipeline contains an extraTreeClassifier and doesn't have SelectFwe. I think, "exported_pipeline.feature_importances_ " should be okay. Can you share your thoughts on the same?

**Comment by weixuanfu** [comment]
@JainVikas What is the exported pipeline? I made up a exported pipeline example based on your question as below. The scikit-learn Pipeline object has the API to access `feature_importances_` in the intermediate step of a Pipeline. But it is noted that the `feature_importances_` in step N would be for features from step N-1 instead of input features for the Pipeline. So if there are feature selection/stacking estimators to exclude/add feature before step N then the `feature_importances_` should have different feature number with input features (X).

```python
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import ExtraTreeClassifier

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25)


exported_pipeline = make_pipeline(
    MinMaxScaler(),
    ExtraTreeClassifier()
)

exported_pipeline.fit(X_train, y_train)
# print steps
print(exported_pipeline.steps)
# getting the  feature importances from step 2 extratreeclassifier
exported_pipeline.named_steps['extratreeclassifier'].feature_importances_```

**Comment by JainVikas** [comment]
yeah, that's pretty accurate. thanks, saw #744 regarding stacking estimator usage.
