### ISSUE TITLE
Scoring functions throw TPOTBase._update_top_pipeline() RuntimeError

### ISSUE THREAD

**Issue by jamesjjcondon** [EpistasisLab/tpot#983]
## Context of the issue

'Accuracy' and 'balanced_accuracy' work fine, but others including f1, recall and precision
throw RuntimeError below

TPOT v11.0
sklearn 21.3

## Process to reproduce the issue

```
from tpot import TPOTClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics.scorer import make_scorer

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
                                                    train_size=0.75, test_size=0.25, random_state=42)

tpot = TPOTClassifier(generations=5, population_size=20, verbosity=2,
                      scoring='f1', n_jobs=-1, random_state=42)

tpot.fit(X_train, y_train)
```

## Expected result

Score piped appropriately, 

## Current result

RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.

## Possible fix

Seems to be related to TPOTBase._update_top_pipeline(). When printing out pipeline and pipeline_scores from line 791 
https://github.com/EpistasisLab/tpot/blob/3d31727e6be5dc80b4dbf1e1835024e861b1eadf/tpot/base.py#L791 
score is `(1.0, -inf)`

Not sure about:
`self._optimized_pipeline_score = -float('inf')`

might be related to [868](https://github.com/EpistasisLab/tpot/issues/868)

Seems to happen regardless of n_jobs.

Any hints much appreciated. 

THANKYOU!!!!

**Comment by weixuanfu** [comment]
The issue may be about using f1_score scorer in multi-class data, which is related to the issue #665. Please try “f1_macro” instead.

**Comment by jamesjjcondon** [comment]
Of course! Thanks so much @weixuanfu . Yep, that was it, sorry. I thought my custom dataset was 2 class, but this made me realise there were nans that were forming a third class. I could do a PR to add to the error message?

**Comment by jamesjjcondon** [comment]
Thanks so much @weixuanfu . Yep, that was it, sorry. I thought my custom dataset was 2 class, but this made me realise there were nans that were forming a third class. I could do a PR to add to the error message?

**Comment by weixuanfu** [comment]
No problem! A PR for an user friendly error message is welcome.

**Comment by josiahjohnston** [comment]
I just ran into this error, and was banging my head on it for a few hours last night. 
Today I tracked it down to a silly mistake in my custom scoring function (I had neglected `import numpy as np`). 
As best I can tell, `tpot.gp_deap:_wrapped_cross_val_score()` is catching all exceptions from _fit_and_score (including errors in the scoring function), and converting them to a score of -inf. When the scoring function is buggy, that results in all individuals having -inf scores and the misleading error message of:
> RuntimeError: There was an error in the TPOT optimization process. This could be because the data was not formatted properly, or because data for a regression problem was provided to the TPOTClassifier object. Please make sure you passed the data to TPOT correctly.

What do you think about making `tpot.gp_deap:_wrapped_cross_val_score()` aware of the verbosity level so it can print the exceptions instead of hiding them. Hiding all exceptions makes code very hard to debug. I'm assuming that the blanket catch is to prune out buggy individuals, but it can have unfortunate side effects for integrating custom scoring (or presumably custom pipeline components).

I just submitted a PR #994 with a minor tweak to the error message. 

Thanks for all your work on this project :)
